// Lighthouse CI configuration

module.exports = {
  ci: {
    collect: {
      url: [
        "http://localhost:3000",
        "http://localhost:3000/portfolio",
        "http://localhost:3000/portfolio/editor/1",
        "http://localhost:3000/portfolio/preview/1",
        "http://localhost:3000/analytics",
        "http://localhost:3000/community",
      ],
      startServerCommand: "npm run start",
      startServerReadyPattern: "ready on",
      startServerReadyTimeout: 30000,
      numberOfRuns: 3,
      settings: {
        chromeFlags:
          "--no-sandbox --disable-dev-shm-usage --disable-gpu --headless",
        preset: "desktop",
        throttling: {
          rttMs: 40,
          throughputKbps: 10240,
          cpuSlowdownMultiplier: 1,
          requestLatencyMs: 0,
          downloadThroughputKbps: 0,
          uploadThroughputKbps: 0,
        },
        skipAudits: [
          "canonical",
          "robots-txt",
          "tap-targets",
          "color-contrast",
          "image-alt",
          "label",
          "link-name",
          "list",
          "listitem",
        ],
      },
    },
    assert: {
      assertions: {
        "categories:performance": ["error", { minScore: 0.9 }],
        "categories:accessibility": ["error", { minScore: 0.9 }],
        "categories:best-practices": ["error", { minScore: 0.9 }],
        "categories:seo": ["error", { minScore: 0.9 }],
        "categories:pwa": ["warn", { minScore: 0.8 }],
        "first-contentful-paint": ["error", { maxNumericValue: 2000 }],
        "largest-contentful-paint": ["error", { maxNumericValue: 2500 }],
        "cumulative-layout-shift": ["error", { maxNumericValue: 0.1 }],
        "total-blocking-time": ["error", { maxNumericValue: 300 }],
        "speed-index": ["error", { maxNumericValue: 3000 }],
        interactive: ["error", { maxNumericValue: 3000 }],
        "max-potential-fid": ["error", { maxNumericValue: 100 }],
        "uses-responsive-images": "off",
        "uses-optimized-images": "off",
        "uses-webp-images": "off",
        "uses-text-compression": "off",
        "uses-long-cache-ttl": "off",
        "total-byte-weight": ["warn", { maxNumericValue: 500000 }],
        "dom-size": ["warn", { maxNumericValue: 1500 }],
        "critical-request-chains": "off",
        "render-blocking-resources": "off",
        "unused-css-rules": "off",
        "unused-javascript": "off",
        "modern-image-formats": "off",
        "offscreen-images": "off",
        "preload-lcp-image": "off",
        "efficient-animated-content": "off",
        "duplicated-javascript": "off",
        "legacy-javascript": "off",
        "no-document-write": "off",
        "no-vulnerable-libraries": "off",
        "csp-xss": "off",
        "external-anchors-use-rel-noopener": "off",
        "geolocation-on-start": "off",
        "notification-on-start": "off",
        "password-inputs-can-be-pasted-into": "off",
        "uses-http2": "off",
        "uses-passive-event-listeners": "off",
      },
    },
    upload: {
      target: "temporary-public-storage",
      githubAppToken: process.env.LHCI_GITHUB_APP_TOKEN,
      githubToken: process.env.GITHUB_TOKEN,
    },
    server: {
      port: 9001,
      storage: "./lighthouse-reports",
    },
  },
};
