# ===========================================
# 🚀 Render Infrastructure as Code for ShowWork
# ===========================================
# This configuration deploys your entire app stack to Render:
# - Backend API
# - Frontend Web App
# - Background Workers
# - Managed MongoDB & Redis
# ===========================================

services:
  # ==========================
  # 🧠 Backend API Service
  # ==========================
  - type: web
    name: showwork-backend
    env: docker
    dockerfilePath: ./Dockerfile.production
    plan: free
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
    autoDeploy: true

  # ==========================
  # 🌐 Frontend Web Service
  # ==========================
  - type: web
    name: showwork-frontend
    env: docker
    dockerfilePath: ./Dockerfile.frontend.production
    plan: free
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://showwork-backend.onrender.com
    autoDeploy: true

  # ==========================
  # ⚙️ Publish Worker
  # ==========================
  - type: worker
    name: showwork-publish-worker
    env: docker
    dockerfilePath: ./Dockerfile.production
    plan: free
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: REDIS_URL
        sync: false
      - key: DATABASE_URL
        sync: false
    command: node src/lib/workers/publish-worker.js
    autoDeploy: true

  # ==========================
  # 📊 Analytics Worker
  # ==========================
